return {
  -- [which-key 딜레이 최적화 및 전체 그룹 라벨 한글화]
  {
    'folke/which-key.nvim',
    opts = {
      delay = 150, -- 팝업 표시 대기 시간을 150ms로 지정 (기본값은 500ms)
      spec = {
        -- ── 최상위 그룹 (Top-level Leader Groups) ──
        -- 그룹명 앞에 [키] 를 표시하여 breadcrumb 타이틀에서 어떤 키를 눌렀는지 직관적으로 확인 가능
        { '<leader>a', group = '[a] AI 에이전트 (CodeCompanion)' },
        { '<leader>b', group = '[b] 버퍼 (Buffer)' },
        { '<leader>c', group = '[c] 코드/LSP (Code)' },
        { '<leader>d', group = '[d] 디버그 (Debug)' },
        { '<leader>f', group = '[f] 파일/검색 (File/Find)' },
        { '<leader>g', group = '[g] 깃 (Git)' },
        { '<leader>m', group = '[m] 미니맵 (Minimap)' },
        { '<leader>q', group = '[q] 종료/세션 (Quit/Session)' },
        { '<leader>s', group = '[s] 문자열/패턴 검색 (Search)' },
        { '<leader>t', group = '[t] 테스트 (Test)' },
        { '<leader>u', group = '[u] UI 설정/토글 (UI)' },
        { '<leader>w', group = '[w] 창 관리 (Windows)' },
        { '<leader>x', group = '[x] 진단/퀵픽스 (Diagnostics/Quickfix)' },
        { '<leader>\\', group = '[\\] 대소문자 변환 (Convert Case)' },
        { '<leader><tab>', group = '[tab] 탭 관리 (Tabs)' },

        -- ── 최상위 단축키 (Top-level Leader Shortcuts) ──
        { '<leader>e', desc = '파일 탐색기 (Explorer Snacks)' },
        { '<leader>E', desc = '현재 위치 탐색기 (Explorer Snacks - CWD)' },
        { '<leader>K', desc = '키워드 도움말 (Keywordprg)' },
        { '<leader>l', desc = '수동 ESLint 실행 (ESLint: Run Manual Lint)' },
        { '<leader>L', desc = 'ESLint 창 닫기 (ESLint: Close Result Window)' },
        { '<leader>n', desc = '알림 기록 (Notification History)' },
        { '<leader>S', desc = '스크래치 버퍼 선택 (Select Scratch Buffer)' },
        { '<leader>,', desc = '열린 버퍼 목록 (Buffers)' },
        { '<leader>-', desc = '창 아래로 분할 (Split Window Below)' },
        { '<leader>.', desc = '스크래치 버퍼 토글 (Toggle Scratch Buffer)' },
        { '<leader>/', desc = '프로젝트 전체 검색 (Grep - Root Dir)' },
        { '<leader>:', desc = '명령어 입력 기록 (Command History)' },
        { '<leader>?', desc = '버퍼 단축키 목록 (Buffer Keymaps)' },
        { '<leader>`', desc = '이전 버퍼로 전환 (Switch to Other Buffer)' },
        { '<leader>|', desc = '창 오른쪽으로 분할 (Split Window Right)' },
        { '<leader><space>', desc = '스마트 파일/버퍼 검색 (Smart Picker)' },

        -- ── AI 에이전트 그룹 (<leader>a / CodeCompanion) ──
        { '<leader>aa', desc = '액션 팔레트 (Action Palette)' },
        { '<leader>ac', desc = '채팅 토글 (Toggle Chat)' },
        { '<leader>ai', desc = '인라인 편집 (Inline Edit)' },
        { '<leader>al', desc = 'CLI 상호작용 (CLI Interaction)' },
        { '<leader>am', desc = '커맨드라인 명령 생성 (Generate Command)' },
        { '<leader>an', desc = '새 채팅 (New Chat)' },
        { '<leader>ar', desc = '코드 리뷰 (Code Review)' },
        { '<leader>av', desc = '선택 영역 채팅에 추가 (Add Selection to Chat)', mode = 'v' },

        -- ── 에이전트 전환 그룹 (<leader>ag) ──
        { '<leader>ag', group = '[g] 에이전트 전환 (Switch Agent)' },
        { '<leader>agc', desc = 'Claude Code로 채팅' },
        { '<leader>agg', desc = 'Gemini CLI로 채팅' },
        { '<leader>ago', desc = 'OpenCode로 채팅' },
        { '<leader>ags', desc = 'Goose로 채팅' },
        { '<leader>agx', desc = 'Codex로 채팅' },

        -- ── 디버그 그룹 (<leader>d) ──
        { '<leader>da', desc = '포트 지정 디버그 연결 (Attach/Launch Debug)' },
        { '<leader>db', desc = '브레이크포인트 설정/해제 (Toggle Breakpoint)' },
        { '<leader>dB', desc = '조건부 브레이크포인트 (Breakpoint Condition)' },
        { '<leader>dc', desc = '커서 위치까지 실행 (Run to Cursor)' },
        { '<leader>dC', desc = '커서 위치까지 실행 (Run to Cursor)' },
        { '<leader>dd', desc = '디버그 실행 / 계속 (Run/Continue)' },
        { '<leader>de', desc = '다음 줄 실행 (Step Over)' },
        { '<leader>dg', desc = '줄 번호로 이동 (Go to Line)' },
        { '<leader>di', desc = '함수 내부 진입 (Step Into)' },
        { '<leader>dj', desc = '아래 스택 이동 (Down)' },
        { '<leader>dk', desc = '위 스택 이동 (Up)' },
        { '<leader>dl', desc = '마지막 디버그 재실행 (Run Last)' },
        { '<leader>do', desc = '함수 밖으로 탈출 (Step Out)' },
        { '<leader>dO', desc = '다음 줄 실행 (Step Over)' },
        { '<leader>dP', desc = '일시 정지 (Pause)' },
        { '<leader>dr', desc = 'REPL 창 토글 (Toggle REPL)' },
        { '<leader>ds', desc = '세션 조작 (Session)' },
        { '<leader>dt', desc = '디버깅 및 서버 종료 (Terminate)' },
        { '<leader>dv', desc = '디버그 UI 토글 (DAP View)' },
        { '<leader>dw', desc = '위젯 창 (Widgets)' },

        -- ── 프로파일러 그룹 (<leader>dp) ──
        { '<leader>dp', group = '[p] 프로파일러 (Profiler)' },
        { '<leader>dph', desc = '프로파일러 하이라이트 토글 (Toggle Profiler Highlights)' },
        { '<leader>dpp', desc = '프로파일러 토글 (Toggle Profiler)' },
        { '<leader>dps', desc = '프로파일러 스크래치 버퍼 (Profiler Scratch Buffer)' },

        -- ── 파일/검색 그룹 (<leader>f) ──
        { '<leader>fb', desc = '버퍼 검색 (Find Buffers)' },
        { '<leader>fB', desc = '전체 버퍼 목록 (Buffers - All)' },
        { '<leader>fc', desc = '설정 파일 찾기 (Find Config File)' },
        { '<leader>fe', desc = '파일 탐색기 - 루트 (Explorer Snacks - Root Dir)' },
        { '<leader>fE', desc = '시스템 파일 탐색기 열기 (Open System Explorer)' },
        { '<leader>ff', desc = '파일 검색 - 루트 (Find Files - Root Dir)' },
        { '<leader>fF', desc = '파일 검색 - 현재 폴더 (Find Files - cwd)' },
        { '<leader>fg', desc = 'Git 파일 검색 (Find Files - git)' },
        { '<leader>fn', desc = '새 파일 생성 (New File)' },
        { '<leader>fp', desc = '프로젝트 목록 (Projects)' },
        { '<leader>fr', desc = '최근 연 파일 - 현재 폴더 (Recent Files)' },
        { '<leader>fR', desc = '최근 연 파일 - 전체 프로젝트 (Recent - Global)' },
        { '<leader>ft', desc = '터미널 - 루트 (Terminal - Root Dir)' },
        { '<leader>fT', desc = '터미널 - 현재 폴더 (Terminal - cwd)' },

        -- ── 깃 그룹 (<leader>g) ──
        { '<leader>gb', desc = 'Git Blame 줄 정보 (Git Blame Line)' },
        { '<leader>gB', desc = 'Git Blame 전체 파일 (Git Blame File)' },
        { '<leader>gc', desc = 'Git 커밋 기록 (Git Commits)' },
        { '<leader>gd', desc = 'Git Diff 분할 (Git Diff)' },
        { '<leader>gD', desc = 'Git Diff - origin 비교 (Git Diff origin)' },
        { '<leader>gf', desc = '현재 파일 Git 히스토리 (Git Current File History)' },
        { '<leader>gg', desc = 'Lazygit - 루트 (Lazygit - Root Dir)' },
        { '<leader>gG', desc = 'Lazygit - 현재 폴더 (Lazygit - cwd)' },
        { '<leader>gi', desc = 'GitHub Issues 열기 (GitHub Issues - open)' },
        { '<leader>gI', desc = 'GitHub Issues 전체 (GitHub Issues - all)' },
        { '<leader>gl', desc = 'Git 로그 (Git Log)' },
        { '<leader>gL', desc = 'Git 로그 - 현재 폴더 (Git Log - cwd)' },
        { '<leader>gp', desc = 'GitHub PR 열기 (GitHub Pull Requests - open)' },
        { '<leader>gP', desc = 'GitHub PR 전체 (GitHub Pull Requests - all)' },
        { '<leader>gq', desc = 'Git Diffview 열기 (Open Git Diffview)' },
        { '<leader>gQ', desc = 'Git Diffview 닫기 (Close Git Diffview)' },
        { '<leader>gs', desc = 'Git 상태 (Git Status)' },
        { '<leader>gS', desc = 'Git Stash' },
        { '<leader>gY', desc = 'Git 브라우저 - 링크 복사 (Git Browse copy)' },

        -- ── Git 변경 조각 그룹 (<leader>gh / Hunks) ──
        { '<leader>gh', group = '[h] Git 변경 조각 (Hunks)' },
        { '<leader>ghb', desc = '줄 Blame 정보 (Blame Line)' },
        { '<leader>ghB', desc = '버퍼 Blame 정보 (Blame Buffer)' },
        { '<leader>ghd', desc = '현재 파일 Diff 비교 (Diff This)' },
        { '<leader>ghD', desc = '이전 커밋과 Diff 비교 (Diff This ~)' },
        { '<leader>ghp', desc = '변경 조각 인라인 미리보기 (Preview Hunk Inline)' },
        { '<leader>ghr', desc = '변경 조각 되돌리기 (Reset Hunk)' },
        { '<leader>ghR', desc = '버퍼 전체 변경 되돌리기 (Reset Buffer)' },
        { '<leader>ghs', desc = '변경 조각 스테이징 (Stage Hunk)' },
        { '<leader>ghS', desc = '버퍼 전체 스테이징 (Stage Buffer)' },
        { '<leader>ghu', desc = '스테이징 취소 (Undo Stage Hunk)' },

        -- ── 노멀 모드 이동 그룹 (g / +goto) ──
        { 'g', group = '[g] 이동 (Goto)' },
        { 'gd', desc = '정의로 이동 (Goto Definition)' },
        { 'gD', desc = '선언으로 이동 (Goto Declaration)' },
        { 'gI', desc = '구현체로 이동 (Goto Implementation)' },
        { 'gK', desc = '시그니처 도움말 (Signature Help)' },
        { 'gy', desc = '타입 정의로 이동 (Goto Type Definition)' },
        { 'gr', group = '[r] 참조 검색 (References)' },
        { 'ge', desc = '이전 단어 끝으로 이동 (Prev end of word)' },
        { 'gf', desc = '커서 위치 파일로 이동 (Go to file under cursor)' },
        { 'gg', desc = '첫 번째 줄로 이동 (First line)' },
        { 'gi', desc = '마지막 입력 위치로 이동 (Go to last insert)' },
        { 'gn', desc = '다음 검색어 찾기 및 선택 (Search forwards and select)' },
        { 'gN', desc = '이전 검색어 찾기 및 선택 (Search backwards and select)' },
        { 'gO', desc = '문서 심볼 목록 (Document Symbols)' },
        { 'gt', desc = '다음 탭으로 이동 (Go to next tab page)' },
        { 'gT', desc = '이전 탭으로 이동 (Go to previous tab page)' },
        { 'gu', desc = '소문자로 변환 (Lowercase)' },
        { 'gU', desc = '대문자로 변환 (Uppercase)' },
        { 'gv', desc = '마지막 비주얼 선택 영역 (Last visual selection)' },
        { 'gw', desc = '코드 포맷팅 (Format)' },
        { 'gX', desc = '외부 시스템 앱으로 열기 (Open with system app)' },
        { 'g%', desc = '이전 결과로 순환 (Cycle backwards through results)' },
        { 'g,', desc = '변경 기록 최신 위치로 이동 (Go to newer position in change list)' },
        { 'g;', desc = '변경 기록 이전 위치로 이동 (Go to older position in change list)' },
        { 'g[', desc = '왼쪽 주변으로 이동 (Move to left "around")' },
        { 'g]', desc = '오른쪽 주변으로 이동 (Move to right "around")' },
        { 'g~', desc = '대소문자 토글 (Toggle case)' },

        -- ── g 하위 호출 계층 그룹 (ga) ──
        { 'ga', group = '[a] 호출 계층 (Call Hierarchy)' },
        { 'gai', desc = '나를 호출하는 함수 목록 (Calls Incoming)' },
        { 'gao', desc = '내가 호출하는 함수 목록 (Calls Outgoing)' },

        -- ── g 하위 주석 그룹 (gc) ──
        { 'gc', group = '[c] 주석 토글 (Toggle comment)' },
        { 'gcc', desc = '현재 줄 주석 토글 (Toggle comment line)' },
        { 'gco', desc = '아래 줄에 주석 추가 (Add Comment Below)' },
        { 'gcO', desc = '위 줄에 주석 추가 (Add Comment Above)' },

        -- ── 노멀 모드 삭제 오퍼레이터 (d / +Delete) ──
        { 'd', group = '[d] 삭제 (Delete)' },
        { 'd0', desc = '줄 시작까지 삭제 (Start of line)' },
        { 'db', desc = '이전 단어 삭제 (Prev word)' },
        { 'dB', desc = '이전 단어(공백 구분) 삭제 (Prev WORD)' },
        { 'de', desc = '단어 끝까지 삭제 (Next end of word)' },
        { 'dE', desc = '단어(공백 구분) 끝까지 삭제 (Next end of WORD)' },
        { 'df', desc = '다음 지정 문자까지 삭제 (Move to next char)' },
        { 'dF', desc = '이전 지정 문자까지 삭제 (Move to prev char)' },
        { 'dG', desc = '마지막 줄까지 삭제 (Last line)' },
        { 'dh', desc = '왼쪽 문자 삭제 (Left)' },
        { 'dj', desc = '아래 줄 삭제 (Down)' },
        { 'dk', desc = '위 줄 삭제 (Up)' },
        { 'dl', desc = '오른쪽 문자 삭제 (Right)' },
        { 'dn', desc = '다음 검색 결과까지 삭제 (Next Search Result)' },
        { 'dN', desc = '이전 검색 결과까지 삭제 (Prev Search Result)' },
        { 'dr', desc = 'Flash 원격 삭제 (Remote Flash)' },
        { 'dR', desc = 'Treesitter 검색 삭제 (Treesitter Search)' },
        { 'ds', desc = 'Flash 위치 삭제 (Flash)' },
        { 'dS', desc = 'Flash Treesitter 위치 삭제 (Flash Treesitter)' },
        { 'dt', desc = '지정 문자 직전까지 삭제 (Move before next char)' },
        { 'dT', desc = '이전 지정 문자 직전까지 삭제 (Move before prev char)' },
        { 'dw', desc = '다음 단어 시작까지 삭제 (Next word)' },
        { 'dW', desc = '다음 단어(공백 구분) 시작까지 삭제 (Next WORD)' },
        { 'd$', desc = '줄 끝까지 삭제 (End of line)' },
        { 'd%', desc = '짝 괄호까지 삭제 (Matching ()^{}[])' },
        { 'd,', desc = '이전 f/t/F/T 위치 삭제 (Prev ftFT)' },
        { 'd/', desc = '검색 패턴 위치까지 삭제 (Search forward)' },
        { 'd;', desc = '다음 f/t/F/T 위치 삭제 (Next ftFT)' },
        { 'd?', desc = '역방향 검색 패턴 위치까지 삭제 (Search backward)' },
        { 'd^', desc = '공백 제외 줄 시작까지 삭제 (Start of line non ws)' },
        { 'd{', desc = '이전 빈 줄까지 삭제 (Prev empty line)' },
        { 'd}', desc = '다음 빈 줄까지 삭제 (Next empty line)' },
        { 'd<space>', desc = 'Treesitter 점진적 선택 범위 삭제 (Treesitter Incremental Selection)' },

        -- ── 노멀 모드 코드 접기/뷰 조절 그룹 (z / +fold) ──
        { 'z', group = '[z] 접기/뷰 조절 (Fold & View)' },
        { 'za', desc = '커서 위치 접기 토글 (Toggle fold under cursor)' },
        { 'zA', desc = '커서 위치 하위 접기 모두 토글 (Toggle all folds under cursor)' },
        { 'zb', desc = '현재 줄을 화면 맨 아래로 (Bottom this line)' },
        { 'zc', desc = '커서 위치 접기 닫기 (Close fold under cursor)' },
        { 'zC', desc = '커서 위치 하위 접기 모두 닫기 (Close all folds under cursor)' },
        { 'zd', desc = '커서 위치 접기 삭제 (Delete fold under cursor)' },
        { 'zD', desc = '커서 위치 하위 접기 모두 삭제 (Delete all folds under cursor)' },
        { 'ze', desc = '현재 줄을 화면 오른쪽으로 (Right this line)' },
        { 'zE', desc = '파일 전체 접기 삭제 (Delete all folds in file)' },
        { 'zf', desc = '접기 범위 생성 (Create fold)' },
        { 'zg', desc = '철자 사전에 단어 추가 (Add word to spell list)' },
        { 'zH', desc = '화면 반 통 왼쪽 이동 (Half screen to the left)' },
        { 'zi', desc = '전체 접기 기능 토글 (Toggle folding)' },
        { 'zL', desc = '화면 반 통 오른쪽 이동 (Half screen to the right)' },
        { 'zm', desc = '접기 레벨 올리기 (Fold more)' },
        { 'zM', desc = '모든 접기 닫기 (Close all folds)' },
        { 'zo', desc = '커서 위치 접기 열기 (Open fold under cursor)' },
        { 'zO', desc = '커서 위치 하위 접기 모두 열기 (Open all folds under cursor)' },
        { 'zr', desc = '접기 레벨 내리기 (Fold less)' },
        { 'zR', desc = '모든 접기 열기 (Open all folds)' },
        { 'zs', desc = '현재 줄을 화면 왼쪽으로 (Left this line)' },
        { 'zt', desc = '현재 줄을 화면 맨 위로 (Top this line)' },
        { 'zv', desc = '커서 위치 접기 펼쳐 보이기 (Show cursor line)' },
        { 'zw', desc = '철자 오류로 단어 표시 (Mark word as bad/misspelling)' },
        { 'zx', desc = '접기 상태 업데이트 (Update folds)' },
        { 'zz', desc = '현재 줄을 화면 중앙으로 (Center this line)' },
        { 'z<cr>', desc = '현재 줄을 화면 맨 위로 (Top this line)' },
        { 'z=', desc = '철자 추천 단어 목록 (Spelling Suggestions)' },

        -- ── 노멀 모드 변경 오퍼레이터 (c / +Change) ──
        { 'c', group = '[c] 변경 (Change)' },
        { 'c0', desc = '줄 시작까지 변경 (Start of line)' },
        { 'cb', desc = '이전 단어 변경 (Prev word)' },
        { 'cB', desc = '이전 단어(공백 구분) 변경 (Prev WORD)' },
        { 'ce', desc = '단어 끝까지 변경 (Next end of word)' },
        { 'cE', desc = '단어(공백 구분) 끝까지 변경 (Next end of WORD)' },
        { 'cf', desc = '다음 지정 문자까지 변경 (Move to next char)' },
        { 'cF', desc = '이전 지정 문자까지 변경 (Move to prev char)' },
        { 'cG', desc = '마지막 줄까지 변경 (Last line)' },
        { 'ch', desc = '왼쪽 문자 변경 (Left)' },
        { 'cj', desc = '아래 줄 변경 (Down)' },
        { 'ck', desc = '위 줄 변경 (Up)' },
        { 'cl', desc = '오른쪽 문자 변경 (Right)' },
        { 'cn', desc = '다음 검색 결과까지 변경 (Next Search Result)' },
        { 'cN', desc = '이전 검색 결과까지 변경 (Prev Search Result)' },
        { 'cr', desc = 'Flash 원격 위치 변경 (Remote Flash)' },
        { 'cR', desc = 'Treesitter 검색 위치 변경 (Treesitter Search)' },
        { 'cs', desc = 'Flash 위치 변경 (Flash)' },
        { 'cS', desc = 'Flash Treesitter 위치 변경 (Flash Treesitter)' },
        { 'ct', desc = '지정 문자 직전까지 변경 (Move before next char)' },
        { 'cT', desc = '이전 지정 문자 직전까지 변경 (Move before prev char)' },
        { 'cw', desc = '다음 단어 시작까지 변경 (Next word)' },
        { 'cW', desc = '다음 단어(공백 구분) 시작까지 변경 (Next WORD)' },
        { 'c$', desc = '줄 끝까지 변경 (End of line)' },
        { 'c%', desc = '짝 괄호까지 변경 (Matching ()^{}[])' },
        { 'c,', desc = '이전 f/t/F/T 위치 변경 (Prev ftFT)' },
        { 'c/', desc = '검색 패턴 위치까지 변경 (Search forward)' },
        { 'c;', desc = '다음 f/t/F/T 위치 변경 (Next ftFT)' },
        { 'c?', desc = '역방향 검색 패턴 위치까지 변경 (Search backward)' },
        { 'c^', desc = '공백 제외 줄 시작까지 변경 (Start of line non ws)' },
        { 'c{', desc = '이전 빈 줄까지 변경 (Prev empty line)' },
        { 'c}', desc = '다음 빈 줄까지 변경 (Next empty line)' },
        { 'c<space>', desc = 'Treesitter 점진적 선택 범위 변경 (Treesitter Incremental Selection)' },

        -- ── 노멀 모드 비주얼 선택 (v / +Visual) ──
        { 'v', group = '[v] 비주얼 선택 (Visual)' },
        { 'v0', desc = '줄 시작까지 선택 (Start of line)' },
        { 'vb', desc = '이전 단어 선택 (Prev word)' },
        { 'vB', desc = '이전 단어(공백 구분) 선택 (Prev WORD)' },
        { 'vc', desc = '변경 모드 (Change)' },
        { 'vd', desc = '삭제 모드 (Delete)' },
        { 've', desc = '단어 끝까지 선택 (Next end of word)' },
        { 'vE', desc = '단어(공백 구분) 끝까지 선택 (Next end of WORD)' },
        { 'vf', desc = '다음 지정 문자까지 선택 (Move to next char)' },
        { 'vF', desc = '이전 지정 문자까지 선택 (Move to prev char)' },
        { 'vG', desc = '마지막 줄까지 선택 (Last line)' },
        { 'vh', desc = '왼쪽 문자 선택 (Left)' },
        { 'vj', desc = '아래 줄 선택 (Down)' },
        { 'vk', desc = '위 줄 선택 (Up)' },
        { 'vl', desc = '오른쪽 문자 선택 (Right)' },
        { 'vn', desc = '다음 검색 결과까지 선택 (Next Search Result)' },
        { 'vN', desc = '이전 검색 결과까지 선택 (Prev Search Result)' },
        { 'vr', desc = '문자 교체 모드 (Replace)' },
        { 'vR', desc = 'Treesitter 검색 선택 (Treesitter Search)' },
        { 'vs', desc = 'Flash 선택 (Flash)' },
        { 'vS', desc = 'Flash Treesitter 선택 (Flash Treesitter)' },
        { 'vt', desc = '지정 문자 직전까지 선택 (Move before next char)' },
        { 'vT', desc = '이전 지정 문자 직전까지 선택 (Move before prev char)' },
        { 'vv', desc = '글자 단위 비주얼 선택 (Visual)' },
        { 'vV', desc = '줄 단위 비주얼 선택 (Visual Line)' },
        { 'vw', desc = '다음 단어 시작까지 선택 (Next word)' },
        { 'vW', desc = '다음 단어(공백 구분) 시작까지 선택 (Next WORD)' },
        { 'vy', desc = '복사 모드 (Yank)' },
        { 'v$', desc = '줄 끝까지 선택 (End of line)' },
        { 'v%', desc = '짝 괄호까지 선택 (Matching ()^{}[])' },
        { 'v,', desc = '이전 f/t/F/T 위치 선택 (Prev ftFT)' },
        { 'v/', desc = '검색 패턴 위치까지 선택 (Search forward)' },
        { 'v;', desc = '다음 f/t/F/T 위치 선택 (Next ftFT)' },
        { 'v<', desc = '들여쓰기 줄이기 (Indent left)' },
        { 'v>', desc = '들여쓰기 늘리기 (Indent right)' },
        { 'v?', desc = '역방향 검색 패턴 위치까지 선택 (Search backward)' },
        { 'v^', desc = '공백 제외 줄 시작까지 선택 (Start of line non ws)' },
        { 'v{', desc = '이전 빈 줄까지 선택 (Prev empty line)' },
        { 'v}', desc = '다음 빈 줄까지 선택 (Next empty line)' },
        { 'v~', desc = '대소문자 반전 (Toggle case)' },

        -- ── 노멀 모드 마크 이동 (' 및 ` / +marks) ──
        { "'", group = "['] 마크 줄 이동 (Jump to mark line)" },
        { '`', group = '[`] 마크 위치 이동 (Jump to mark exact)' },

        -- ── 미니맵 그룹 (<leader>m) ──
        { '<leader>mf', desc = '미니맵 포커스 토글 (Toggle Focus Minimap)' },
        { '<leader>mm', desc = '미니맵 토글 (Toggle Minimap)' },

        -- ── 종료/세션 그룹 (<leader>q) ──
        { '<leader>qd', desc = "세션 저장 안 하고 종료 (Don't Save Current Session)" },
        { '<leader>ql', desc = '마지막 세션 복원 (Restore Last Session)' },
        { '<leader>qq', desc = '모두 종료 (Quit All)' },
        { '<leader>qs', desc = '현재 세션 복원 (Restore Session)' },
        { '<leader>qS', desc = '세션 선택 (Select Session)' },

        -- ── 코드/LSP 그룹 (<leader>c) ──
        { '<leader>ca', desc = '코드 액션 (Code Action)' },
        { '<leader>cA', desc = '소스 코드 액션 (Source Action)' },
        { '<leader>cc', desc = 'CodeLens 실행 (Run Codelens)' },
        { '<leader>cC', desc = 'CodeLens 새로고침 (Refresh & Display Codelens)' },
        { '<leader>cd', desc = '진단 정보 보기 (Line Diagnostics)' },
        { '<leader>cf', desc = '코드 포맷팅 (Format Code)' },
        { '<leader>cF', desc = '삽입 언어 포맷 (Format Injected Langs)' },
        { '<leader>cl', desc = 'LSP 설정 정보 (Lsp Info)' },
        { '<leader>cm', desc = 'Mason 패키지 관리자 (Mason)' },
        -- 💡 nvim-treesitter-textobjects: 파라미터 순서 교환 (Swap)
        -- ⚠️ 단축키를 변경할 경우 `lua/plugins/treesitter.lua`의 textobjects.swap 설정도 반드시 함께 변경해야 합니다.
        { '<leader>cp', desc = '다음 파라미터와 교환 (Swap Next Parameter)' },
        { '<leader>cP', desc = '이전 파라미터와 교환 (Swap Prev Parameter)' },
        { '<leader>cr', desc = '심볼 이름 변경 (Rename Symbol)' },
        { '<leader>cR', desc = '파일 이름 변경 (Rename File)' },
        { '<leader>cs', desc = '심볼 목록 - Trouble (Symbols - Trouble)' },
        { '<leader>cS', desc = 'LSP 참조/정의 목록 - Trouble (LSP Refs/Defs - Trouble)' },
        { '<leader>cv', desc = 'Python 가상환경 선택 (Select VirtualEnv)' },

        -- ── 문자열/패턴 검색 그룹 (<leader>s) ──
        { '<leader>sa', desc = '자동 명령 목록 (Autocmds)' },
        { '<leader>sb', desc = '현재 버퍼 문자열 검색 (Buffer Lines)' },
        { '<leader>sB', desc = '열린 버퍼 목록 검색 (Grep Open Buffers)' },
        { '<leader>sc', desc = '명령 입력 기록 (Command History)' },
        { '<leader>sC', desc = 'Neovim 명령어 목록 (Commands)' },
        { '<leader>sd', desc = '프로젝트 진단 목록 (Diagnostics)' },
        { '<leader>sD', desc = '버퍼 진단 목록 (Buffer Diagnostics)' },
        { '<leader>sg', desc = '프로젝트 전체 검색 (Grep - Root Dir)' },
        { '<leader>sG', desc = '현재 폴더 전체 검색 (Grep - cwd)' },
        { '<leader>sh', desc = '도움말 페이지 검색 (Help Pages)' },
        { '<leader>sH', desc = '하이라이트 그룹 검색 (Highlights)' },
        { '<leader>si', desc = '아이콘 검색 (Icons)' },
        { '<leader>sj', desc = '점프 목록 (Jumps)' },
        { '<leader>sk', desc = '단축키 목록 (Keymaps)' },
        { '<leader>sl', desc = '위치 목록 (Location List)' },
        { '<leader>sm', desc = '마크 목록 (Marks)' },
        { '<leader>sM', desc = '매뉴얼 페이지 검색 (Man Pages)' },
        { '<leader>sn', group = '[n] Noice 알림' },
        { '<leader>sna', desc = 'Noice 전체 메시지 (Noice All)' },
        { '<leader>snh', desc = 'Noice 기록 (Noice History)' },
        { '<leader>snl', desc = 'Noice 마지막 메시지 (Noice Last Message)' },
        { '<leader>snd', desc = 'Noice 알림 모두 닫기 (Dismiss All)' },
        { '<leader>snt', desc = 'Noice 피커 열기 (Noice Picker)' },
        { '<leader>sp', desc = '플러그인 스펙 검색 (Search Plugin Spec)' },
        { '<leader>sq', desc = '퀵픽스 목록 (Quickfix List)' },
        { '<leader>sr', desc = '문자열 찾기/바꾸기 (Search and Replace)' },
        { '<leader>sR', desc = '이전 검색 재개 (Resume)' },
        { '<leader>ss', desc = 'LSP 심볼 검색 - 현재 버퍼 (LSP Symbols)' },
        { '<leader>sS', desc = 'LSP 심볼 검색 - 전체 프로젝트 (LSP Workspace Symbols)' },
        { '<leader>st', desc = 'TODO 항목 검색 (Todo)' },
        { '<leader>sT', desc = 'TODO/FIX/FIXME 검색 (Todo/Fix/Fixme)' },
        { '<leader>su', desc = '되돌리기 트리 (Undotree)' },
        { '<leader>sw', desc = '현재 단어 검색 - 프로젝트 (Search Word - Root Dir)' },
        { '<leader>sW', desc = '현재 단어 검색 - 현재 폴더 (Search Word - cwd)' },
        { '<leader>s"', desc = '레지스터 목록 (Registers)' },
        { '<leader>s/', desc = '검색 기록 (Search History)' },

        -- ── 버퍼 그룹 (<leader>b) ──
        { '<leader>bb', desc = '이전 버퍼로 전환 (Switch to Other Buffer)' },
        { '<leader>bd', desc = '현재 버퍼 닫기 (Delete Buffer)' },
        { '<leader>bD', desc = '버퍼와 창 함께 닫기 (Delete Buffer and Window)' },
        { '<leader>bi', desc = '숨겨진 버퍼 모두 닫기 (Delete Invisible Buffers)' },
        { '<leader>bj', desc = '버퍼 선택 (Pick Buffer)' },
        { '<leader>bl', desc = '왼쪽 버퍼 모두 닫기 (Delete Buffers to the Left)' },
        { '<leader>bo', desc = '다른 버퍼 모두 닫기 (Close Other Buffers)' },
        { '<leader>bp', desc = '버퍼 고정 토글 (Toggle Pin)' },
        { '<leader>bP', desc = '고정 안 된 버퍼 모두 닫기 (Delete Non-Pinned Buffers)' },
        { '<leader>br', desc = '오른쪽 버퍼 모두 닫기 (Delete Buffers to the Right)' },

        -- ── 창 관리 그룹 (<leader>w) ──
        { '<leader>wd', desc = '현재 창 닫기 (Close Window)' },
        { '<leader>wm', desc = '줌 모드 활성화 (Enable Zoom Mode)' },
        { '<leader>ws', desc = '창 아래로 분할 (Split Below)' },
        { '<leader>wv', desc = '창 오른쪽 분할 (Split Right)' },
        { '<leader>ww', desc = '다른 창으로 이동 (Other Window)' },

        -- ── 진단/퀵픽스 그룹 (<leader>x) ──
        { '<leader>xl', desc = '위치 목록 (Location List)' },
        { '<leader>xL', desc = '위치 목록 - Trouble (Location List - Trouble)' },
        { '<leader>xq', desc = '퀵픽스 목록 (Quickfix List)' },
        { '<leader>xQ', desc = '퀵픽스 목록 - Trouble (Quickfix List - Trouble)' },
        { '<leader>xt', desc = 'TODO 목록 - Trouble (Todo - Trouble)' },
        { '<leader>xT', desc = 'TODO/FIX/FIXME - Trouble (Todo/Fix/Fixme - Trouble)' },
        { '<leader>xx', desc = 'Trouble 진단 창 (Diagnostics)' },
        { '<leader>xX', desc = '버퍼 진단 창 (Buffer Diagnostics)' },

        -- ── UI 설정/토글 그룹 (<leader>u) ──
        { '<leader>ua', desc = '애니메이션 비활성화 (Disable Animations)' },
        { '<leader>uA', desc = '탭라인 활성화 (Enable Tabline)' },
        { '<leader>ub', desc = '어두운 배경 비활성화 (Disable Dark Background)' },
        { '<leader>uc', desc = '테마 변경 (Colorscheme)' },
        { '<leader>uC', desc = '컬러 스킴 목록 (Colorschemes)' },
        { '<leader>ud', desc = '진단 비활성화 (Disable Diagnostics)' },
        { '<leader>uD', desc = '딤 모드 활성화 (Enable Dimming)' },
        { '<leader>uf', desc = '자동 포맷팅 토글 (Auto Format)' },
        { '<leader>uF', desc = '버퍼 자동 포맷 비활성화 (Disable Auto Format - Buffer)' },
        { '<leader>ug', desc = '들여쓰기 가이드 활성화 (Enable Indent Guides)' },
        { '<leader>uh', desc = '인레이 힌트 활성화 (Enable Inlay Hints)' },
        { '<leader>ui', desc = '현재 위치 정보 (Inspect Pos)' },
        { '<leader>uI', desc = '트리 정보 (Inspect Tree)' },
        { '<leader>ul', desc = '줄 번호 활성화 (Enable Line Numbers)' },
        { '<leader>uL', desc = '상대 줄 번호 활성화 (Enable Relative Number)' },
        { '<leader>um', desc = '마크다운 렌더링 토글 (Disable Render Markdown)' },
        { '<leader>un', desc = '줄 번호 토글 (Line Numbers)' },
        { '<leader>up', desc = '미니 쌍 비활성화 (Disable Mini Pairs)' },
        { '<leader>ur', desc = '화면 새로고침 (Redraw / Clear hlsearch / Diff Update)' },
        { '<leader>us', desc = '철자 검사 토글 (Spelling)' },
        { '<leader>uS', desc = '부드러운 스크롤 비활성화 (Disable Smooth Scroll)' },
        { '<leader>uT', desc = 'Treesitter 하이라이트 활성화 (Enable Treesitter Highlight)' },
        { '<leader>uw', desc = '줄 바꿈 활성화 (Enable Wrap)' },
        { '<leader>uz', desc = '젠 모드 활성화 (Enable Zen Mode)' },
        { '<leader>uZ', desc = '줌 모드 활성화 (Enable Zoom Mode)' },

        -- ── 테스트 그룹 (<leader>t / Neotest) ──
        { '<leader>ta', desc = '테스트 러너 연결 (Attach to Test)' },
        { '<leader>td', desc = '가장 가까운 테스트 디버그 (Debug Nearest)' },
        { '<leader>tl', desc = '마지막 테스트 재실행 (Run Last)' },
        { '<leader>to', desc = '테스트 결과 출력 (Show Output)' },
        { '<leader>tO', desc = '출력 패널 토글 (Toggle Output Panel)' },
        { '<leader>tr', desc = '가장 가까운 테스트 실행 (Run Nearest)' },
        { '<leader>ts', desc = '테스트 요약 토글 (Toggle Summary)' },
        { '<leader>tS', desc = '테스트 중지 (Stop)' },
        { '<leader>tt', desc = '현재 파일 테스트 실행 (Run File)' },
        { '<leader>tT', desc = '전체 테스트 파일 실행 (Run All Test Files)' },
        { '<leader>tw', desc = '테스트 감시 모드 토글 (Toggle Watch)' },

        -- ── 대소문자 변환 그룹 (<leader>\) ── (convert-case)
        { '<leader>\\a', desc = 'Unicode 디코드 (Decode \\uXXXX → char)' },
        { '<leader>\\A', desc = 'Unicode 인코드 (Encode char → \\uXXXX)' },
        { '<leader>\\c', desc = 'camelCase로 변환 (toCamelCase)' },
        { '<leader>\\C', desc = 'LSP 이름 변경: camelCase (LSP rename toCamelCase)' },
        { '<leader>\\d', desc = 'dash-case로 변환 (to-dash-case)' },
        { '<leader>\\D', desc = 'LSP 이름 변경: dash-case (LSP rename to-dash-case)' },
        { '<leader>\\l', desc = '소문자로 변환 (to lower case)' },
        { '<leader>\\L', desc = 'LSP 이름 변경: 소문자 (LSP rename to lower case)' },
        { '<leader>\\n', desc = 'CONSTANT_CASE로 변환 (TO_CONSTANT_CASE)' },
        { '<leader>\\N', desc = 'LSP 이름 변경: CONSTANT_CASE (LSP rename TO_CONSTANT_CASE)' },
        { '<leader>\\p', desc = 'PascalCase로 변환 (ToPascalCase)' },
        { '<leader>\\P', desc = 'LSP 이름 변경: PascalCase (LSP rename ToPascalCase)' },
        { '<leader>\\s', desc = 'snake_case로 변환 (to_snake_case)' },
        { '<leader>\\S', desc = 'LSP 이름 변경: snake_case (LSP rename to_snake_case)' },
        { '<leader>\\t', desc = 'Title Case로 변환 (To Title Case)' },
        { '<leader>\\u', desc = '대문자로 변환 (TO UPPER CASE)' },
        { '<leader>\\U', desc = 'LSP 이름 변경: 대문자 (LSP rename TO UPPER CASE)' },
        { '<leader>\\w', desc = 'phrase case로 변환 (to phrase case)' },
        { '<leader>\\o', group = '[o] 모션 지정 변환 (Motion Operator)' },
        { '<leader>\\oc', desc = 'camelCase 모션 변환 (toCamelCase motion)' },
        { '<leader>\\od', desc = 'dash-case 모션 변환 (to-dash-case motion)' },
        { '<leader>\\ol', desc = '소문자 모션 변환 (to lower case motion)' },
        { '<leader>\\on', desc = 'CONSTANT_CASE 모션 변환 (TO_CONSTANT_CASE motion)' },
        { '<leader>\\op', desc = 'PascalCase 모션 변환 (ToPascalCase motion)' },
        { '<leader>\\os', desc = 'snake_case 모션 변환 (to_snake_case motion)' },
        { '<leader>\\ou', desc = '대문자 모션 변환 (TO UPPER CASE motion)' },

        -- ── 탭 관리 그룹 (<leader><tab>) ──
        { '<leader><tab>d', desc = '현재 탭 닫기 (Close Tab)' },
        { '<leader><tab>f', desc = '첫 번째 탭으로 이동 (First Tab)' },
        { '<leader><tab>l', desc = '마지막 탭으로 이동 (Last Tab)' },
        { '<leader><tab>o', desc = '다른 탭 모두 닫기 (Close Other Tabs)' },
        { '<leader><tab>[', desc = '이전 탭으로 이동 (Previous Tab)' },
        { '<leader><tab>]', desc = '다음 탭으로 이동 (Next Tab)' },
        { '<leader><tab><tab>', desc = '새 탭 열기 (New Tab)' },
      },
    },
  },
}
